[build]
  command = "npm ci && npx prisma generate && npm run build"
  publish = "build/client"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "shopify.app.toml,.env,.env.local,.env.production,build/**,README.md,Dockerfile"
  SECRETS_SCAN_OMIT_KEYS = "NODE_ENV,SHOPIFY_APP_URL,SHOPIFY_API_KEY,SHOPIFY_CLIENT_ID"
  NODE_ENV = "production"

[functions]
  directory = "netlify/functions"
  # Increase timeout for optimization functions
  timeout = 60
  # Set memory limit for better performance
  memory = 1024

# Correct MIME types for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"

# Static assets should be served directly
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Routing is handled automatically by the Netlify Remix adapter plugin