[build]
  publish = "build/client"
  command = "npm ci && npx prisma generate && npm run build"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "shopify.app.toml,.env,.env.local,.env.production,build/**,README.md,Dockerfile"
  SECRETS_SCAN_OMIT_KEYS = "NODE_ENV,SHOPIFY_APP_URL,SHOPIFY_API_KEY,SHOPIFY_CLIENT_ID"
  NODE_ENV = "production"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@shopify/shopify-app-remix", "@prisma/client", "react", "react-dom"]
  included_files = [".env*"]

[[redirects]]
  from = "/__manifest"
  to = "/.netlify/functions/server"
  status = 200

# Serve static assets from build/client
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Serve favicon and other static files
[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200

# Send all other requests to the server function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"