[build]
  publish = "build/client"
  command = "npm install && npx prisma generate && npm run build"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "shopify.app.toml,.env,.env.local,.env.production,build/**,README.md,Dockerfile"
  SECRETS_SCAN_OMIT_KEYS = "NODE_ENV", "SHOPIFY_APP_URL"
  NODE_ENV = "production"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@shopify/shopify-app-remix", "@prisma/client"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"