[build]
  command = "npm ci && npx prisma generate && npm run build"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "shopify.app.toml,.env,.env.local,.env.production,build/**,README.md,Dockerfile"
  SECRETS_SCAN_OMIT_KEYS = "NODE_ENV,SHOPIFY_APP_URL,SHOPIFY_API_KEY,SHOPIFY_CLIENT_ID"
  NODE_ENV = "production"

# The Netlify Remix adapter will handle the functions configuration automatically