# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fa9d90437a467b7215e296d9eb003d7d"
name = "b1: Bulk Product SEO Optimizer"
handle = "b1-bulk-product-seo-optimizer"
application_url = "https://florida-protocols-pdt-lived.trycloudflare.com"
# For local development, you'll need to use ngrok or update this to your local tunnel URL
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app-subscriptions/update"

  # Mandatory compliance webhooks for Shopify App Store
  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "/webhooks"



[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_product_listings,write_product_listings"

[auth]
redirect_urls = ["https://florida-protocols-pdt-lived.trycloudflare.com/auth/callback", "https://florida-protocols-pdt-lived.trycloudflare.com/auth/shopify/callback", "https://florida-protocols-pdt-lived.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
